DROP DATABASE IF EXISTS Target_Inventory_Database;
CREATE DATABASE Target_Inventory_Database;
USE Target_Inventory_Database;
CREATE TABLE ITEM (
    DPCI      			INT 			NOT NULL PRIMARY KEY,
    TRUCK_ID 			INT 			NOT NULL,
    DEPARTMENT_NAME 	VARCHAR(15) 	NOT NULL,
	RECIEPT_NUMBER 		INT 			NULL,
    DEFECT_ID 			INT 			NULL
	); 
CREATE TABLE TRUCK_ORDER (
    TRUCK_ID 			INT 			NOT NULL PRIMARY KEY,
    TRUCK_DATE_TIME 	TIMESTAMP 		NOT NULL,
    DPCI 				INT 			NOT NULL,
    CONSTRAINT TRUCK_ORDER_FK			FOREIGN KEY (DPCI)	REFERENCES ITEM(DPCI)

	);
CREATE TABLE DEPARTMENT (
    DEPARTMENT_NAME 	VARCHAR(15) 	NOT NULL PRIMARY KEY,
	EMP_ID 				INT		 		NOT NULL
	);
CREATE TABLE EMPLOYEE(
	EMP_ID 				INT 			NOT NULL PRIMARY KEY,
	EMP_NAME 			VARCHAR(30) 	NOT NULL,
	DEPARTMENT_NAME 	VARCHAR(15) 	NOT NULL,
    CONSTRAINT EMPLOYEE_FK				FOREIGN KEY (DEPARTMENT_NAME) REFERENCES DEPARTMENT(DEPARTMENT_NAME)

	);
CREATE TABLE RECEIPT(
    RECEIPT_NUMBER 		INT 			NOT NULL PRIMARY KEY,
    DPCI 				INT 			NOT NULL,
    SALE_ID 			INT 			NULL,
    RETURN_ID 			INT 			NULL,
	DEFECT_ID			INT				NULL
	);
CREATE TABLE DEFECT(
	RECEIPT_NUMBER 		INT 			NOT NULL PRIMARY KEY,
	DEFECT_DATE_TIME 	TIMESTAMP 		NOT NULL,
	CONSTRAINT DEFECT_FK				FOREIGN KEY (RECEIPT_NUMBER) REFERENCES RECEIPT(RECEIPT_NUMBER)
   );

CREATE TABLE SALE(
    RECEIPT_NUMBER 		INT 			NOT NULL PRIMARY KEY,
    SALE_DATE_TIME 		TIMESTAMP 		NOT NULL,
	CONSTRAINT SALE_FK				FOREIGN KEY (RECEIPT_NUMBER) REFERENCES RECEIPT(RECEIPT_NUMBER)
    );
CREATE TABLE I_RETURN(
    RECEIPT_NUMBER 		INT 			NOT NULL PRIMARY KEY,
    RETURN_DATE_TIME 	TIMESTAMP 		NOT NULL,
	CONSTRAINT RETURN_FK				FOREIGN KEY (RECEIPT_NUMBER) REFERENCES RECEIPT(RECEIPT_NUMBER)
    );

